spring:
  cloud:
    stream:
      bindings:
        output:
          destination: ex.stream.out
          group: test
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbit
                port: 5672
                username: config
                password: config
                